# Generated by Django 6.0.4 on 2026-04-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='baseline_unit',
            field=models.CharField(blank=True, default='m', max_length=50, null=True, verbose_name='Единицы измерения'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='baseline_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='diagnosis',
            field=models.TextField(blank=True, null=True, verbose_name='Диагноз (ввод врача)'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='limitation_type',
            field=models.TextField(blank=True, null=True, verbose_name='Тип ограничения (ввод врача)'),
        ),
    ]
